vich_uploader:
  db_driver: orm

  mappings:
    pictures:
      uri_prefix: /images/pictures
      upload_destination: '%kernel.project_dir%/public/photos/pictures'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
